Step 137 expokit update
bitrise-io/bitrise-init pull request #195
Opened 2020-12-15 13:36 UTC by lpusok

2021-01-07 12:57 UTC, godrei requested changes
Pls check my comments

2021-01-07 15:14 UTC, lpusok commented on _tests/integration/android_test.go
> +func gitCloneBranch(t *testing.T, dir, uri, branch string) {
If we suppose the default branch can be hardcoded as master, then it is possible.

2021-01-07 16:08 UTC, lpusok commented on _tests/integration/manual_config_test.go
> +                    type: user_input_optional
No it is not, but used this option as allows to set a default value like: `./ios/< PROJECT NAME >.xcworkspace`

2021-01-07 16:10 UTC, lpusok commented on scanners/reactnative/expo.go
> +		if androidNode != nil {
It was possible originally, but not at the moment as did not find a way to determine if ios/android is used by parsing app.json.

2021-01-08 07:59 UTC, lpusok commented on _tests/integration/android_test.go
> +func gitCloneBranch(t *testing.T, dir, uri, branch string) {
Did not change as for example iOS App Clip sample uses main branch.

2021-01-08 07:59 UTC, lpusok commented on _tests/integration/manual_config_test.go
> +                      Needed to eject to the bare workflow, managed workflow is not
Reworded.

2021-01-08 07:59 UTC, lpusok commented on _tests/integration/manual_config_test.go
> +                    type: user_input_optional
Decided to remove the default value, and the optional.

2021-01-08 08:00 UTC, lpusok commented on _tests/integration/manual_config_test.go
> +                      ./ios/< PROJECT NAME >.xcworkspace:
It was valid, but only as a  default value that can be changed. Decided to remove it.

2021-01-08 08:01 UTC, lpusok commented on scanners/reactnative/expo.go
> +	log.TPrintf("Project name: %v", scanner.expoSettings.name)
Moved after precondition check.

2021-01-08 08:01 UTC, lpusok commented on scanners/reactnative/expo.go
> +		rootNode = androidNode
Added precondition check at the beginning of the function.

2021-01-08 12:19 UTC, godrei requested changes
pls see my comment

2021-01-08 12:19 UTC, godrei commented on scanners/reactnative/reactnative.go
> +	errorMessage := `To eject native projects non-interactively, the Expo project app.json file needs to contain:
these fields are not required currently

2021-01-08 14:07 UTC, lpusok commented on scanners/reactnative/expo.go
> +		developmentTeamOption := models.NewOption(iosDevelopmentTeamInputTitle, iosDevelopmentTeamInputSummary, "BITRISE_IOS_DEVELOPMENT_TEAM", models.TypeUserInput)
Moved

2021-01-08 14:08 UTC, lpusok commented on scanners/reactnative/expo.go
> +			projectSettingNode = models.NewOption(projectRootDirInputTitle, projectRootDirInputSummary, "WORKDIR", models.TypeSelector)
Moved

2021-01-08 14:08 UTC, lpusok commented on scanners/reactnative/reactnative.go
> +	errorMessage := `To eject native projects non-interactively, the Expo project app.json file needs to contain:
Discussed, improved logging.

2021-01-08 14:10 UTC, godrei approved these changes

2021-01-08 14:17 UTC, merged